# PostgreSQL. Versions 8.2 and up are supported.

default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: Backend_development

test:
  <<: *default
  database: Backend_test

production:
  <<: *default
  database: Backend_production
  username: Backend
  password: <%= ENV['BACKEND_DATABASE_PASSWORD'] %>
